[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "8D1Efb1EwVahXe3h1Qj21PtrECuEN3GNPnARdEU6tRE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
voteInit = "npx tsx app/initializeVoteAccount.ts"
vote = "npx tsx app/vote.ts"
